CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: copilot_copilotpatch; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.copilot_copilotpatch (
    id bigint NOT NULL,
    patch_id character varying(64) NOT NULL,
    base_version integer NOT NULL,
    operation_type character varying(64) NOT NULL,
    content_preview text NOT NULL,
    rationale text,
    status character varying(32) NOT NULL,
    review_comment text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    doctor_id bigint NOT NULL,
    encounter_id bigint NOT NULL,
    run_id bigint NOT NULL,
    target_document_id bigint NOT NULL,
    source_context_document_ids jsonb NOT NULL,
    target_selection_reason text,
    anchor jsonb NOT NULL,
    document_preview_after text,
    expected_hash character varying(128),
    target_document_title character varying(255),
    confidence double precision,
    conflict_reason text,
    new_text text,
    old_text text,
    order_index integer NOT NULL,
    patch_set_id bigint,
    patch_type character varying(64) NOT NULL,
    resolved_end integer,
    resolved_start integer,
    section character varying(128),
    replacement_text text,
    inserted_text text
);


--
-- Name: copilot_copilotpatch_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.copilot_copilotpatch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.copilot_copilotpatch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: copilot_copilotpatchset; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.copilot_copilotpatchset (
    id bigint NOT NULL,
    patch_set_id character varying(64) NOT NULL,
    base_version integer NOT NULL,
    base_hash character varying(128) NOT NULL,
    rationale text,
    source_context_document_ids jsonb NOT NULL,
    target_document_title character varying(255),
    target_selection_reason text,
    document_preview_after text,
    status character varying(32) NOT NULL,
    review_comment text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    doctor_id bigint NOT NULL,
    encounter_id bigint NOT NULL,
    run_id bigint NOT NULL,
    target_document_id bigint NOT NULL,
    affected_sections jsonb NOT NULL,
    clinical_impact_level character varying(32),
    edit_scope character varying(32)
);


--
-- Name: copilot_copilotpatchset_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.copilot_copilotpatchset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.copilot_copilotpatchset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: copilot_copilotrun; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.copilot_copilotrun (
    id bigint NOT NULL,
    run_id character varying(64) NOT NULL,
    thread_id character varying(255) NOT NULL,
    status character varying(32) NOT NULL,
    intent character varying(64),
    requires_human_review boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    doctor_id bigint NOT NULL,
    encounter_id bigint NOT NULL
);


--
-- Name: copilot_copilotrun_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.copilot_copilotrun ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.copilot_copilotrun_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents_document; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents_document (
    id bigint NOT NULL,
    kind character varying(20) NOT NULL,
    content_markdown text NOT NULL,
    created_on date NOT NULL,
    doctor_id bigint NOT NULL,
    doctor_template_id bigint,
    encounter_id bigint NOT NULL,
    content_json jsonb
);


--
-- Name: documents_document_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documents_document ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: encounters_encounter; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.encounters_encounter (
    id bigint NOT NULL,
    patient_connected boolean NOT NULL,
    encounter_name character varying(255),
    occurred_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    audio_file_name character varying(255),
    audio_uploaded_at timestamp with time zone,
    audio_expires_at timestamp with time zone,
    audio_duration_seconds integer,
    has_been_transcribed boolean NOT NULL,
    doctor_id bigint NOT NULL,
    patient_id bigint
);


--
-- Name: encounters_encounter_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.encounters_encounter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.encounters_encounter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients_patient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patients_patient (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    summary text,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: patients_patient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.patients_patient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patients_patient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients_patientdoctor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patients_patientdoctor (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    doctor_id bigint NOT NULL,
    patient_id bigint NOT NULL
);


--
-- Name: patients_patientdoctor_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.patients_patientdoctor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patients_patientdoctor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: templates_basetemplate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.templates_basetemplate (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    document_kind character varying(50) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: templates_basetemplate_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.templates_basetemplate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.templates_basetemplate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: templates_doctortemplate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.templates_doctortemplate (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    document_kind character varying(50) NOT NULL,
    uses_base_content boolean NOT NULL,
    content text,
    created_at timestamp with time zone NOT NULL,
    base_template_id bigint,
    doctor_id bigint NOT NULL
);


--
-- Name: templates_doctortemplate_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.templates_doctortemplate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.templates_doctortemplate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: templates_templateusage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.templates_templateusage (
    id bigint NOT NULL,
    use_count integer NOT NULL,
    last_used_at timestamp with time zone,
    doctor_id bigint NOT NULL,
    doctor_template_id bigint NOT NULL,
    CONSTRAINT templates_templateusage_use_count_check CHECK ((use_count >= 0))
);


--
-- Name: templates_templateusage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.templates_templateusage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.templates_templateusage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    email character varying(254) NOT NULL,
    name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    role character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: copilot_copilotpatch copilot_copilotpatch_patch_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatch
    ADD CONSTRAINT copilot_copilotpatch_patch_id_key UNIQUE (patch_id);


--
-- Name: copilot_copilotpatch copilot_copilotpatch_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatch
    ADD CONSTRAINT copilot_copilotpatch_pkey PRIMARY KEY (id);


--
-- Name: copilot_copilotpatchset copilot_copilotpatchset_patch_set_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatchset
    ADD CONSTRAINT copilot_copilotpatchset_patch_set_id_key UNIQUE (patch_set_id);


--
-- Name: copilot_copilotpatchset copilot_copilotpatchset_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatchset
    ADD CONSTRAINT copilot_copilotpatchset_pkey PRIMARY KEY (id);


--
-- Name: copilot_copilotrun copilot_copilotrun_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotrun
    ADD CONSTRAINT copilot_copilotrun_pkey PRIMARY KEY (id);


--
-- Name: copilot_copilotrun copilot_copilotrun_run_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotrun
    ADD CONSTRAINT copilot_copilotrun_run_id_key UNIQUE (run_id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: documents_document documents_document_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents_document
    ADD CONSTRAINT documents_document_pkey PRIMARY KEY (id);


--
-- Name: encounters_encounter encounters_encounter_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.encounters_encounter
    ADD CONSTRAINT encounters_encounter_pkey PRIMARY KEY (id);


--
-- Name: patients_patient patients_patient_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patient
    ADD CONSTRAINT patients_patient_pkey PRIMARY KEY (id);


--
-- Name: patients_patientdoctor patients_patientdoctor_doctor_id_patient_id_00c18d59_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patientdoctor
    ADD CONSTRAINT patients_patientdoctor_doctor_id_patient_id_00c18d59_uniq UNIQUE (doctor_id, patient_id);


--
-- Name: patients_patientdoctor patients_patientdoctor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patientdoctor
    ADD CONSTRAINT patients_patientdoctor_pkey PRIMARY KEY (id);


--
-- Name: templates_basetemplate templates_basetemplate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.templates_basetemplate
    ADD CONSTRAINT templates_basetemplate_pkey PRIMARY KEY (id);


--
-- Name: templates_doctortemplate templates_doctortemplate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.templates_doctortemplate
    ADD CONSTRAINT templates_doctortemplate_pkey PRIMARY KEY (id);


--
-- Name: templates_templateusage templates_templateusage_doctor_template_id_docto_0585d332_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.templates_templateusage
    ADD CONSTRAINT templates_templateusage_doctor_template_id_docto_0585d332_uniq UNIQUE (doctor_template_id, doctor_id);


--
-- Name: templates_templateusage templates_templateusage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.templates_templateusage
    ADD CONSTRAINT templates_templateusage_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: copilot_cop_doctor__553b6b_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_cop_doctor__553b6b_idx ON public.copilot_copilotrun USING btree (doctor_id, encounter_id);


--
-- Name: copilot_cop_doctor__6f0cd0_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_cop_doctor__6f0cd0_idx ON public.copilot_copilotpatch USING btree (doctor_id, encounter_id);


--
-- Name: copilot_cop_run_id_468f25_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_cop_run_id_468f25_idx ON public.copilot_copilotpatch USING btree (run_id, status);


--
-- Name: copilot_cop_target__1321e5_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_cop_target__1321e5_idx ON public.copilot_copilotpatch USING btree (target_document_id);


--
-- Name: copilot_cop_thread__60ab29_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_cop_thread__60ab29_idx ON public.copilot_copilotrun USING btree (thread_id);


--
-- Name: copilot_copilotpatch_doctor_id_c904bd99; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotpatch_doctor_id_c904bd99 ON public.copilot_copilotpatch USING btree (doctor_id);


--
-- Name: copilot_copilotpatch_encounter_id_3abdde0b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotpatch_encounter_id_3abdde0b ON public.copilot_copilotpatch USING btree (encounter_id);


--
-- Name: copilot_copilotpatch_patch_id_a16f5190_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotpatch_patch_id_a16f5190_like ON public.copilot_copilotpatch USING btree (patch_id varchar_pattern_ops);


--
-- Name: copilot_copilotpatch_patch_set_id_9a80a1f1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotpatch_patch_set_id_9a80a1f1 ON public.copilot_copilotpatch USING btree (patch_set_id);


--
-- Name: copilot_copilotpatch_run_id_8fc3263e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotpatch_run_id_8fc3263e ON public.copilot_copilotpatch USING btree (run_id);


--
-- Name: copilot_copilotpatch_target_document_id_90e22a71; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotpatch_target_document_id_90e22a71 ON public.copilot_copilotpatch USING btree (target_document_id);


--
-- Name: copilot_copilotpatchset_doctor_id_4e5de278; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotpatchset_doctor_id_4e5de278 ON public.copilot_copilotpatchset USING btree (doctor_id);


--
-- Name: copilot_copilotpatchset_encounter_id_d76360ea; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotpatchset_encounter_id_d76360ea ON public.copilot_copilotpatchset USING btree (encounter_id);


--
-- Name: copilot_copilotpatchset_patch_set_id_95f067e7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotpatchset_patch_set_id_95f067e7_like ON public.copilot_copilotpatchset USING btree (patch_set_id varchar_pattern_ops);


--
-- Name: copilot_copilotpatchset_run_id_a68bcd6a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotpatchset_run_id_a68bcd6a ON public.copilot_copilotpatchset USING btree (run_id);


--
-- Name: copilot_copilotpatchset_target_document_id_31f9a6ff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotpatchset_target_document_id_31f9a6ff ON public.copilot_copilotpatchset USING btree (target_document_id);


--
-- Name: copilot_copilotrun_doctor_id_bdaf9b61; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotrun_doctor_id_bdaf9b61 ON public.copilot_copilotrun USING btree (doctor_id);


--
-- Name: copilot_copilotrun_encounter_id_f00fa913; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotrun_encounter_id_f00fa913 ON public.copilot_copilotrun USING btree (encounter_id);


--
-- Name: copilot_copilotrun_run_id_1d0c9e0b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_copilotrun_run_id_1d0c9e0b_like ON public.copilot_copilotrun USING btree (run_id varchar_pattern_ops);


--
-- Name: copilot_patch_pset_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_patch_pset_status_idx ON public.copilot_copilotpatch USING btree (patch_set_id, status);


--
-- Name: copilot_pset_doctor_enc_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_pset_doctor_enc_idx ON public.copilot_copilotpatchset USING btree (doctor_id, encounter_id);


--
-- Name: copilot_pset_run_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_pset_run_status_idx ON public.copilot_copilotpatchset USING btree (run_id, status);


--
-- Name: copilot_pset_target_doc_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX copilot_pset_target_doc_idx ON public.copilot_copilotpatchset USING btree (target_document_id);


--
-- Name: documents_document_doctor_id_2f5e3e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX documents_document_doctor_id_2f5e3e4b ON public.documents_document USING btree (doctor_id);


--
-- Name: documents_document_doctor_template_id_56af8169; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX documents_document_doctor_template_id_56af8169 ON public.documents_document USING btree (doctor_template_id);


--
-- Name: documents_document_encounter_id_3c65e7b7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX documents_document_encounter_id_3c65e7b7 ON public.documents_document USING btree (encounter_id);


--
-- Name: encounters__doctor__aa839a_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX encounters__doctor__aa839a_idx ON public.encounters_encounter USING btree (doctor_id);


--
-- Name: encounters__patient_9f10b2_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX encounters__patient_9f10b2_idx ON public.encounters_encounter USING btree (patient_id);


--
-- Name: encounters_encounter_doctor_id_b91df284; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX encounters_encounter_doctor_id_b91df284 ON public.encounters_encounter USING btree (doctor_id);


--
-- Name: encounters_encounter_patient_id_68c640cf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX encounters_encounter_patient_id_68c640cf ON public.encounters_encounter USING btree (patient_id);


--
-- Name: patients_pa_doctor__a46108_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_pa_doctor__a46108_idx ON public.patients_patientdoctor USING btree (doctor_id);


--
-- Name: patients_pa_patient_b340a5_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_pa_patient_b340a5_idx ON public.patients_patientdoctor USING btree (patient_id);


--
-- Name: patients_patientdoctor_doctor_id_eab9dc20; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patientdoctor_doctor_id_eab9dc20 ON public.patients_patientdoctor USING btree (doctor_id);


--
-- Name: patients_patientdoctor_patient_id_f414ff6b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX patients_patientdoctor_patient_id_f414ff6b ON public.patients_patientdoctor USING btree (patient_id);


--
-- Name: templates_b_documen_2e7919_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX templates_b_documen_2e7919_idx ON public.templates_basetemplate USING btree (document_kind);


--
-- Name: templates_d_base_te_7b540d_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX templates_d_base_te_7b540d_idx ON public.templates_doctortemplate USING btree (base_template_id);


--
-- Name: templates_d_doctor__dbb177_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX templates_d_doctor__dbb177_idx ON public.templates_doctortemplate USING btree (doctor_id);


--
-- Name: templates_d_documen_4f6178_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX templates_d_documen_4f6178_idx ON public.templates_doctortemplate USING btree (document_kind);


--
-- Name: templates_doctortemplate_base_template_id_cf8408f7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX templates_doctortemplate_base_template_id_cf8408f7 ON public.templates_doctortemplate USING btree (base_template_id);


--
-- Name: templates_doctortemplate_doctor_id_f632a60a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX templates_doctortemplate_doctor_id_f632a60a ON public.templates_doctortemplate USING btree (doctor_id);


--
-- Name: templates_t_doctor__523c11_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX templates_t_doctor__523c11_idx ON public.templates_templateusage USING btree (doctor_id);


--
-- Name: templates_t_doctor__fd160e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX templates_t_doctor__fd160e_idx ON public.templates_templateusage USING btree (doctor_template_id);


--
-- Name: templates_templateusage_doctor_id_bd177a33; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX templates_templateusage_doctor_id_bd177a33 ON public.templates_templateusage USING btree (doctor_id);


--
-- Name: templates_templateusage_doctor_template_id_cf2eea7a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX templates_templateusage_doctor_template_id_cf2eea7a ON public.templates_templateusage USING btree (doctor_template_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: copilot_copilotpatch copilot_copilotpatch_doctor_id_c904bd99_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatch
    ADD CONSTRAINT copilot_copilotpatch_doctor_id_c904bd99_fk_users_user_id FOREIGN KEY (doctor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: copilot_copilotpatch copilot_copilotpatch_encounter_id_3abdde0b_fk_encounter; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatch
    ADD CONSTRAINT copilot_copilotpatch_encounter_id_3abdde0b_fk_encounter FOREIGN KEY (encounter_id) REFERENCES public.encounters_encounter(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: copilot_copilotpatchset copilot_copilotpatch_encounter_id_d76360ea_fk_encounter; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatchset
    ADD CONSTRAINT copilot_copilotpatch_encounter_id_d76360ea_fk_encounter FOREIGN KEY (encounter_id) REFERENCES public.encounters_encounter(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: copilot_copilotpatch copilot_copilotpatch_patch_set_id_9a80a1f1_fk_copilot_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatch
    ADD CONSTRAINT copilot_copilotpatch_patch_set_id_9a80a1f1_fk_copilot_c FOREIGN KEY (patch_set_id) REFERENCES public.copilot_copilotpatchset(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: copilot_copilotpatch copilot_copilotpatch_run_id_8fc3263e_fk_copilot_copilotrun_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatch
    ADD CONSTRAINT copilot_copilotpatch_run_id_8fc3263e_fk_copilot_copilotrun_id FOREIGN KEY (run_id) REFERENCES public.copilot_copilotrun(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: copilot_copilotpatchset copilot_copilotpatch_run_id_a68bcd6a_fk_copilot_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatchset
    ADD CONSTRAINT copilot_copilotpatch_run_id_a68bcd6a_fk_copilot_c FOREIGN KEY (run_id) REFERENCES public.copilot_copilotrun(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: copilot_copilotpatchset copilot_copilotpatch_target_document_id_31f9a6ff_fk_documents; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatchset
    ADD CONSTRAINT copilot_copilotpatch_target_document_id_31f9a6ff_fk_documents FOREIGN KEY (target_document_id) REFERENCES public.documents_document(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: copilot_copilotpatch copilot_copilotpatch_target_document_id_90e22a71_fk_documents; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatch
    ADD CONSTRAINT copilot_copilotpatch_target_document_id_90e22a71_fk_documents FOREIGN KEY (target_document_id) REFERENCES public.documents_document(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: copilot_copilotpatchset copilot_copilotpatchset_doctor_id_4e5de278_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotpatchset
    ADD CONSTRAINT copilot_copilotpatchset_doctor_id_4e5de278_fk_users_user_id FOREIGN KEY (doctor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: copilot_copilotrun copilot_copilotrun_doctor_id_bdaf9b61_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotrun
    ADD CONSTRAINT copilot_copilotrun_doctor_id_bdaf9b61_fk_users_user_id FOREIGN KEY (doctor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: copilot_copilotrun copilot_copilotrun_encounter_id_f00fa913_fk_encounter; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.copilot_copilotrun
    ADD CONSTRAINT copilot_copilotrun_encounter_id_f00fa913_fk_encounter FOREIGN KEY (encounter_id) REFERENCES public.encounters_encounter(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_document documents_document_doctor_id_2f5e3e4b_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents_document
    ADD CONSTRAINT documents_document_doctor_id_2f5e3e4b_fk_users_user_id FOREIGN KEY (doctor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_document documents_document_doctor_template_id_56af8169_fk_templates; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents_document
    ADD CONSTRAINT documents_document_doctor_template_id_56af8169_fk_templates FOREIGN KEY (doctor_template_id) REFERENCES public.templates_doctortemplate(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: documents_document documents_document_encounter_id_3c65e7b7_fk_encounter; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents_document
    ADD CONSTRAINT documents_document_encounter_id_3c65e7b7_fk_encounter FOREIGN KEY (encounter_id) REFERENCES public.encounters_encounter(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: encounters_encounter encounters_encounter_doctor_id_b91df284_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.encounters_encounter
    ADD CONSTRAINT encounters_encounter_doctor_id_b91df284_fk_users_user_id FOREIGN KEY (doctor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: encounters_encounter encounters_encounter_patient_id_68c640cf_fk_patients_patient_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.encounters_encounter
    ADD CONSTRAINT encounters_encounter_patient_id_68c640cf_fk_patients_patient_id FOREIGN KEY (patient_id) REFERENCES public.patients_patient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patients_patientdoctor patients_patientdoct_patient_id_f414ff6b_fk_patients_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patientdoctor
    ADD CONSTRAINT patients_patientdoct_patient_id_f414ff6b_fk_patients_ FOREIGN KEY (patient_id) REFERENCES public.patients_patient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: patients_patientdoctor patients_patientdoctor_doctor_id_eab9dc20_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients_patientdoctor
    ADD CONSTRAINT patients_patientdoctor_doctor_id_eab9dc20_fk_users_user_id FOREIGN KEY (doctor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: templates_doctortemplate templates_doctortemp_base_template_id_cf8408f7_fk_templates; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.templates_doctortemplate
    ADD CONSTRAINT templates_doctortemp_base_template_id_cf8408f7_fk_templates FOREIGN KEY (base_template_id) REFERENCES public.templates_basetemplate(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: templates_doctortemplate templates_doctortemplate_doctor_id_f632a60a_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.templates_doctortemplate
    ADD CONSTRAINT templates_doctortemplate_doctor_id_f632a60a_fk_users_user_id FOREIGN KEY (doctor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: templates_templateusage templates_templateus_doctor_template_id_cf2eea7a_fk_templates; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.templates_templateusage
    ADD CONSTRAINT templates_templateus_doctor_template_id_cf2eea7a_fk_templates FOREIGN KEY (doctor_template_id) REFERENCES public.templates_doctortemplate(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: templates_templateusage templates_templateusage_doctor_id_bd177a33_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.templates_templateusage
    ADD CONSTRAINT templates_templateusage_doctor_id_bd177a33_fk_users_user_id FOREIGN KEY (doctor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

CREATE TABLE public.fastapi_revoked_token (
    id integer NOT NULL,
    jti character varying(64) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone NOT NULL
);


--
-- Name: fastapi_revoked_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.fastapi_revoked_token_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: fastapi_revoked_token_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.fastapi_revoked_token_id_seq OWNED BY public.fastapi_revoked_token.id;


--
-- Name: fastapi_revoked_token id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fastapi_revoked_token ALTER COLUMN id SET DEFAULT nextval('public.fastapi_revoked_token_id_seq'::regclass);


--
-- Name: fastapi_revoked_token fastapi_revoked_token_jti_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fastapi_revoked_token
    ADD CONSTRAINT fastapi_revoked_token_jti_key UNIQUE (jti);


--
-- Name: fastapi_revoked_token fastapi_revoked_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fastapi_revoked_token
    ADD CONSTRAINT fastapi_revoked_token_pkey PRIMARY KEY (id);


--
-- Name: ix_fastapi_revoked_token_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_fastapi_revoked_token_expires_at ON public.fastapi_revoked_token USING btree (expires_at);


--
-- Name: ix_fastapi_revoked_token_jti; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX ix_fastapi_revoked_token_jti ON public.fastapi_revoked_token USING btree (jti);


--
-- PostgreSQL database dump complete
--

