# Generated by Django 5.1.6 on 2025-03-04 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encuentro', '0002_alter_encuentro_fecha'),
        ('plantillas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contexto', 'Contexto'), ('transcripcion', 'Transcripción'), ('plantilla', 'Plantilla')], max_length=20)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('id_encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='encuentro.encuentro')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
                ('id_plantilla_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='plantillas.plantilladoctor')),
            ],
        ),
    ]
