# Generated by Django 5.1.6 on 2025-03-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("contexto", "Contexto"),
                    ("transcripcion", "Transcripción"),
                    ("plantilla", "Plantilla"),
                    ("nota", "Nota"),
                ],
                max_length=20,
            ),
        ),
    ]
