import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Ubuntu } from "next/font/google";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const funFont = Ubuntu({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-fun",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`min-h-screen bg-background font-sans antialiased ${fontSans.variable} ${funFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
