version: "3.8"

services:
  transcribe_audio_save_db:
    build:
      context: ./transcribe_audio_save_db
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - ENVIRONMENT=local
    env_file:
      - ./transcribe_audio_save_db/.env.local
    volumes:
      - ./credentials:/app/credentials:ro
    networks:
      - cloud-function-network

networks:
  cloud-function-network:
    driver: bridge
