# Generated by Django 5.1.15 on 2026-03-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_connected", models.BooleanField(default=False)),
                (
                    "encounter_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("audio_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("audio_expires_at", models.DateTimeField(blank=True, null=True)),
                ("audio_duration_seconds", models.IntegerField(blank=True, null=True)),
                ("has_been_transcribed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
