# Generated by Django 5.1.6 on 2025-03-21 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantillas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsoPlantilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("veces_usada", models.PositiveIntegerField(default=0)),
                ("ultimo_uso", models.DateTimeField(blank=True, null=True)),
                (
                    "id_medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos_plantillas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos",
                        to="plantillas.plantilladoctor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["id_plantilla"], name="plantillas__id_plan_5837bd_idx"
                    ),
                    models.Index(
                        fields=["id_medico"], name="plantillas__id_medi_9c0178_idx"
                    ),
                ],
                "unique_together": {("id_plantilla", "id_medico")},
            },
        ),
    ]
