# Generated by Django 5.1.6 on 2025-03-03 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_conectado', models.BooleanField(default=False)),
                ('nombre_encuentro', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuentros', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_medico'], name='encuentro_e_id_medi_866981_idx'), models.Index(fields=['id_paciente'], name='encuentro_e_id_paci_d75317_idx')],
            },
        ),
    ]
