# Generated by Django 5.1.6 on 2025-03-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
