# Generated by Django 5.1.6 on 2025-03-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encuentro", "0002_alter_encuentro_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="encuentro",
            name="audio_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="encuentro",
            name="audio_file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="encuentro",
            name="audio_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
