# Generated by Django 5.1.6 on 2025-03-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "encuentro",
            "0003_encuentro_audio_expires_at_encuentro_audio_file_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="encuentro",
            name="audio_duration_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
