# Generated by Django 5.1.6 on 2025-04-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuentro', '0004_encuentro_audio_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='has_been_transcribed',
            field=models.BooleanField(default=False),
        ),
    ]
