# Generated by Django 5.1.15 on 2026-03-29 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BaseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("note", "Nota"),
                            ("document", "Documento"),
                            ("other", "Otros"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document_kind"], name="templates_b_documen_2e7919_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DoctorTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("note", "Nota"),
                            ("document", "Documento"),
                            ("other", "Otros"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("uses_base_content", models.BooleanField(default=False)),
                ("content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "base_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_templates",
                        to="templates.basetemplate",
                    ),
                ),
            ],
        ),
    ]
