# Generated by Django 5.1.15 on 2026-03-29 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("templates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doctortemplate",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templateusage",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="templateusage",
            name="doctor_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usage_records",
                to="templates.doctortemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="doctortemplate",
            index=models.Index(
                fields=["doctor"], name="templates_d_doctor__dbb177_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctortemplate",
            index=models.Index(
                fields=["document_kind"], name="templates_d_documen_4f6178_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctortemplate",
            index=models.Index(
                fields=["base_template"], name="templates_d_base_te_7b540d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templateusage",
            index=models.Index(
                fields=["doctor_template"], name="templates_t_doctor__fd160e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templateusage",
            index=models.Index(
                fields=["doctor"], name="templates_t_doctor__523c11_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templateusage",
            unique_together={("doctor_template", "doctor")},
        ),
    ]
