# Generated by Django 5.1.6 on 2025-03-04 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('nota', 'Nota'), ('documento', 'Documento'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tipo_documento'], name='plantillas__tipo_do_313b9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlantillaDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('nota', 'Nota'), ('documento', 'Documento'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('contenido_base', models.BooleanField(default=False)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_doctor', to=settings.AUTH_USER_MODEL)),
                ('id_plantilla_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_derivadas', to='plantillas.plantillabase')),
            ],
            options={
                'indexes': [models.Index(fields=['id_medico'], name='plantillas__id_medi_57f753_idx'), models.Index(fields=['tipo_documento'], name='plantillas__tipo_do_ed5d1b_idx'), models.Index(fields=['id_plantilla_base'], name='plantillas__id_plan_4690bf_idx')],
            },
        ),
    ]
