# Generated by Django 5.1.15 on 2026-04-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copilot", "0006_copilotpatchset_and_granular_patches"),
    ]

    operations = [
        migrations.AddField(
            model_name="copilotpatch",
            name="section",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="copilotpatchset",
            name="affected_sections",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="copilotpatchset",
            name="clinical_impact_level",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="copilotpatchset",
            name="edit_scope",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
