# Generated by Django 5.1.6 on 2025-03-03 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientemedico',
            name='id_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pacientemedico',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
        ),
        migrations.AddIndex(
            model_name='pacientemedico',
            index=models.Index(fields=['id_medico'], name='pacientes_p_id_medi_03aa20_idx'),
        ),
        migrations.AddIndex(
            model_name='pacientemedico',
            index=models.Index(fields=['id_paciente'], name='pacientes_p_id_paci_e11792_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pacientemedico',
            unique_together={('id_medico', 'id_paciente')},
        ),
    ]
