from __future__ import annotations

from typing import Any


EVIDENCE_SCHEMA: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "quote": {"type": "string"},
        "supports_fields": {"type": "array", "items": {"type": "string"}},
        "chunk_hint": {"type": ["string", "null"]},
    },
    "required": ["quote", "supports_fields", "chunk_hint"],
}

FACT_SCHEMA: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "concept_raw_text": {"type": ["string", "null"]},
        "text_raw": {"type": ["string", "null"]},
        "value_raw": {"type": ["string", "null"]},
        "unit_raw": {"type": ["string", "null"]},
        "event_kind": {
            "type": ["string", "null"],
            "enum": [
                "symptom",
                "negative_symptom",
                "episode",
                "fall_or_possible_fall",
                "confusion_episode",
                "patient_action",
                "treatment_response",
                "other_explicit",
                None,
            ],
        },
        "body_site_raw": {"type": ["string", "null"]},
        "laterality_raw": {"type": ["string", "null"]},
        "severity_raw": {"type": ["string", "null"]},
        "onset_raw": {"type": ["string", "null"]},
        "duration_raw": {"type": ["string", "null"]},
        "time_expression_raw": {"type": ["string", "null"]},
        "name_raw": {"type": ["string", "null"]},
        "dose_value": {"type": ["string", "null"]},
        "dose_unit": {"type": ["string", "null"]},
        "route_raw": {"type": ["string", "null"]},
        "frequency_raw": {"type": ["string", "null"]},
        "timing_raw": {"type": ["string", "null"]},
        "exposure_duration_raw": {"type": ["string", "null"]},
        "prescribed_duration_raw": {"type": ["string", "null"]},
        "adherence_raw": {"type": ["string", "null"]},
        "substance_raw": {"type": ["string", "null"]},
        "reaction_raw": {"type": ["string", "null"]},
        "category": {"type": ["string", "null"]},
        "result_content_raw": {"type": ["string", "null"]},
        "type_raw": {"type": ["string", "null"]},
        "decision_status": {"type": ["string", "null"]},
        "execution_status": {"type": ["string", "null"]},
        "reason_raw": {"type": ["string", "null"]},
        "conditional_on_raw_text": {"type": ["string", "null"]},
        "information_source_role": {
            "type": ["string", "null"],
            "enum": [
                "patient",
                "companion",
                "clinician",
                "prior_record",
                "other_explicit",
                None,
            ],
        },
        "subject_role": {
            "type": ["string", "null"],
            "enum": [
                "patient",
                "companion",
                "family_member",
                "clinician",
                "other_explicit",
                None,
            ],
        },
        "subject_raw_text": {"type": ["string", "null"]},
        "assertion": {
            "type": "string",
            "enum": [
                "present",
                "absent",
                "uncertain",
                "conditional",
                "unknown_to_source",
            ],
        },
        "claim_lifecycle": {
            "type": "string",
            "enum": ["active", "superseded", "retracted"],
        },
        "reported_certainty": {
            "type": ["string", "null"],
            "enum": ["stated_plainly", "hedged", "uncertain", None],
        },
        "evidence": {"type": "array", "items": EVIDENCE_SCHEMA},
    },
    "required": [
        "concept_raw_text",
        "text_raw",
        "value_raw",
        "unit_raw",
        "event_kind",
        "body_site_raw",
        "laterality_raw",
        "severity_raw",
        "onset_raw",
        "duration_raw",
        "time_expression_raw",
        "name_raw",
        "dose_value",
        "dose_unit",
        "route_raw",
        "frequency_raw",
        "timing_raw",
        "exposure_duration_raw",
        "prescribed_duration_raw",
        "adherence_raw",
        "substance_raw",
        "reaction_raw",
        "category",
        "result_content_raw",
        "type_raw",
        "decision_status",
        "execution_status",
        "reason_raw",
        "conditional_on_raw_text",
        "information_source_role",
        "subject_role",
        "subject_raw_text",
        "assertion",
        "claim_lifecycle",
        "reported_certainty",
        "evidence",
    ],
}

SUMMARY_SCHEMA: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "assertion": {
            "type": ["string", "null"],
            "enum": ["none_reported", "some_reported", None],
        },
        "scope_raw_text": {"type": ["string", "null"]},
        "evidence": {"type": "array", "items": EVIDENCE_SCHEMA},
    },
    "required": ["assertion", "scope_raw_text", "evidence"],
}

CLINICAL_FACTS_SCHEMA: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "information_sources": {"type": "array", "items": FACT_SCHEMA},
        "chief_complaints": {"type": "array", "items": FACT_SCHEMA},
        "clinical_events": {"type": "array", "items": FACT_SCHEMA},
        "history": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "conditions": {"type": "array", "items": FACT_SCHEMA},
                "surgeries_and_procedures": {"type": "array", "items": FACT_SCHEMA},
                "trauma": {"type": "array", "items": FACT_SCHEMA},
                "family_history": {"type": "array", "items": FACT_SCHEMA},
                "gynecologic_obstetric": {"type": "array", "items": FACT_SCHEMA},
                "social_history": {"type": "array", "items": FACT_SCHEMA},
                "exposures": {"type": "array", "items": FACT_SCHEMA},
                "unclassified_explicit_history_facts": {
                    "type": "array",
                    "items": FACT_SCHEMA,
                },
            },
            "required": [
                "conditions",
                "surgeries_and_procedures",
                "trauma",
                "family_history",
                "gynecologic_obstetric",
                "social_history",
                "exposures",
                "unclassified_explicit_history_facts",
            ],
        },
        "allergies": {"type": "array", "items": FACT_SCHEMA},
        "allergy_summary": SUMMARY_SCHEMA,
        "medications": {"type": "array", "items": FACT_SCHEMA},
        "medication_summary": SUMMARY_SCHEMA,
        "objective_data": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "vital_signs": {"type": "array", "items": FACT_SCHEMA},
                "anthropometrics": {"type": "array", "items": FACT_SCHEMA},
                "physical_exam_findings": {"type": "array", "items": FACT_SCHEMA},
            },
            "required": [
                "vital_signs",
                "anthropometrics",
                "physical_exam_findings",
            ],
        },
        "diagnostic_studies": {"type": "array", "items": FACT_SCHEMA},
        "interventions": {"type": "array", "items": FACT_SCHEMA},
        "clinician_assessment": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "stated_impressions": {"type": "array", "items": FACT_SCHEMA},
                "stated_diagnoses": {"type": "array", "items": FACT_SCHEMA},
                "stated_differentials": {"type": "array", "items": FACT_SCHEMA},
                "stated_risk_assessments": {"type": "array", "items": FACT_SCHEMA},
            },
            "required": [
                "stated_impressions",
                "stated_diagnoses",
                "stated_differentials",
                "stated_risk_assessments",
            ],
        },
        "care_plan": {"type": "array", "items": FACT_SCHEMA},
        "data_quality": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "corrections": {"type": "array", "items": FACT_SCHEMA},
                "unresolved_conflicts": {"type": "array", "items": FACT_SCHEMA},
            },
            "required": ["corrections", "unresolved_conflicts"],
        },
        "custom_facts": {"type": "array", "items": FACT_SCHEMA},
    },
    "required": [
        "information_sources",
        "chief_complaints",
        "clinical_events",
        "history",
        "allergies",
        "allergy_summary",
        "medications",
        "medication_summary",
        "objective_data",
        "diagnostic_studies",
        "interventions",
        "clinician_assessment",
        "care_plan",
        "data_quality",
        "custom_facts",
    ],
}
